# .circleci/config.yml
version: 2.1

defaults: &defaults
  docker:
    - image: cimg/base:2020.01
  working_directory: ~/project


commands: # a reusable command with parameters
  greeting:
    parameters:
      to:
        type: string
        default: "world"
    steps:
      - run: echo "Hello <<parameters.to>>"

workflows:
  workspace:
    jobs:
      - build
      - save_hello_world_output:
          requires:
            - build
      - print_output_file:
          requires:
            - save_hello_world_output

jobs:

  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: "echo an env var that is part of our project"
          command: |
            echo $MY_ENV_VAR

  save_hello_world_output:
    <<: *defaults
    steps:
#      - run: mkdir -p workspace
      - run: echo "hello world" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths: 
            - output.txt
            
  print_output_file:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt
      - greeting:
          to: "Islam Yassein"
