version: 2.1

workflows:
  workspace:
    jobs:
      - build
      - save_hello_world_output:
          requires:
            - build
      - print_output_file:
          requires:
            - save_hello_world_output



jobs:
  build:
    docker:
#     - image: circleci/node:13.8.0  -->  circleci/ is deprecated
      - image: cimg/base:2020.01
    steps:
      - checkout
      - run:
          name: "echo an env var that is part of our project"
          command: |
            echo $MY_ENV_VAR
  save_hello_world_output:
    docker:
      - image: cimg/base:2020.01
    steps:
#      - run: mkdir -p workspace
      - run: echo "hello world" > ~/output.txt
      - persist_to_workspace:
          root: ~/
          paths: 
            - output.txt
  print_output_file:
    docker:
      - image: cimg/base:2020.01
    steps:
      - attach_workspace:
          at: ~/
      - run: cat ~/output.txt
